function buildPharmacyDocs(ctx) {
    const { pharmacyA, pharmacyB, pharmacyC } = ctx.identities;

    const pharmacyProfiles = [
        {
            id: ctx.buildDocId("pharmacy", "greenleaf"),
            owner: pharmacyA,
            name: "GreenLeaf Pharmacy",
            address: "12 Residency Road",
            city: "Bengaluru",
            state: "Karnataka",
            zipCode: "560025",
            latitude: 12.9718,
            longitude: 77.6412,
            operatingHours: "Mon-Sat: 08:00-22:00, Sun: 09:00-18:00",
            isDeliveryAvailable: true,
            isActive: true,
            rating: 4.7,
            ratingCount: 426,
            estimatedDeliveryTime: "30-45 min",
            services: ["Prescription", "Home Delivery", "Vaccination"],
            verificationStatus: "APPROVED",
            createdAt: ctx.dateAt(-50, 10, 0),
        },
        {
            id: ctx.buildDocId("pharmacy", "wellcare"),
            owner: pharmacyB,
            name: "WellCare Drugs",
            address: "88 Lake View Street",
            city: "Bengaluru",
            state: "Karnataka",
            zipCode: "560034",
            latitude: 12.9375,
            longitude: 77.6269,
            operatingHours: "Mon-Sat: 09:00-21:00",
            isDeliveryAvailable: true,
            isActive: true,
            rating: 4.2,
            ratingCount: 119,
            estimatedDeliveryTime: "45-60 min",
            services: ["Generic Medicines", "OTC", "Refill Packaging"],
            verificationStatus: "PENDING",
            createdAt: ctx.dateAt(-22, 11, 10),
        },
        {
            id: ctx.buildDocId("pharmacy", "nightplus"),
            owner: pharmacyC,
            name: "NightPlus Meds",
            address: "5 Market Cross",
            city: "Bengaluru",
            state: "Karnataka",
            zipCode: "560016",
            latitude: 13.0125,
            longitude: 77.6408,
            operatingHours: "24x7",
            isDeliveryAvailable: false,
            isActive: false,
            rating: 3.8,
            ratingCount: 54,
            estimatedDeliveryTime: "N/A",
            services: ["Emergency Pickup", "Overnight Support"],
            verificationStatus: "REJECTED",
            createdAt: ctx.dateAt(-18, 9, 30),
        },
    ];

    const docs = [];

    for (const profile of pharmacyProfiles) {
        docs.push(
            ctx.makeSeedDoc(
                "pharmacies",
                `pharmacies/${profile.id}`,
                ctx.withSeedMeta({
                    name: profile.name,
                    address: profile.address,
                    city: profile.city,
                    state: profile.state,
                    zipCode: profile.zipCode,
                    phone: profile.owner.phoneNumber,
                    email: profile.owner.email,
                    latitude: profile.latitude,
                    longitude: profile.longitude,
                    operatingHours: profile.operatingHours,
                    isDeliveryAvailable: profile.isDeliveryAvailable,
                    isActive: profile.isActive,
                    rating: profile.rating,
                    ratingCount: profile.ratingCount,
                    imageUrl: "",
                    estimatedDeliveryTime: profile.estimatedDeliveryTime,
                    services: profile.services,
                    ownerId: profile.owner.uid,
                    licenseNumber: `LIC-${profile.id.toUpperCase().slice(-8)}`,
                    licenseDocumentUrl: `https://example.com/licenses/${profile.id}.pdf`,
                    verificationStatus: profile.verificationStatus,
                    createdAt: profile.createdAt,
                    updatedAt: ctx.now,
                }),
                [profile.owner.uid]
            )
        );
    }

    const inventoryRows = [
        {
            key: "a_metformin",
            pharmacyId: pharmacyProfiles[0].id,
            medicineName: "Metformin",
            dosage: "500mg",
            genericName: "Metformin Hydrochloride",
            category: "Diabetes",
            manufacturer: "Sun Pharma",
            batch: "MF2401",
            stockQuantity: 120,
            unitPrice: 8.5,
            unit: "tablets",
            lowStockThreshold: 20,
            expiryDays: 180,
            isActive: true,
        },
        {
            key: "a_amlodipine",
            pharmacyId: pharmacyProfiles[0].id,
            medicineName: "Amlodipine",
            dosage: "5mg",
            genericName: "Amlodipine Besylate",
            category: "Blood Pressure",
            manufacturer: "Cipla",
            batch: "AM2319",
            stockQuantity: 8,
            unitPrice: 6.75,
            unit: "tablets",
            lowStockThreshold: 10,
            expiryDays: 120,
            isActive: true,
        },
        {
            key: "a_atorvastatin",
            pharmacyId: pharmacyProfiles[0].id,
            medicineName: "Atorvastatin",
            dosage: "10mg",
            genericName: "Atorvastatin Calcium",
            category: "Cholesterol",
            manufacturer: "Dr Reddy's",
            batch: "AT2208",
            stockQuantity: 0,
            unitPrice: 9.25,
            unit: "tablets",
            lowStockThreshold: 12,
            expiryDays: 90,
            isActive: true,
        },
        {
            key: "a_insulin",
            pharmacyId: pharmacyProfiles[0].id,
            medicineName: "Insulin Glargine",
            dosage: "100IU",
            genericName: "Insulin Glargine",
            category: "Diabetes",
            manufacturer: "Sanofi",
            batch: "IG2410",
            stockQuantity: 15,
            unitPrice: 685,
            unit: "pen",
            lowStockThreshold: 8,
            expiryDays: 14,
            isActive: true,
        },
        {
            key: "a_amoxicillin",
            pharmacyId: pharmacyProfiles[0].id,
            medicineName: "Amoxicillin",
            dosage: "500mg",
            genericName: "Amoxicillin",
            category: "Antibiotic",
            manufacturer: "Mankind",
            batch: "AX2011",
            stockQuantity: 5,
            unitPrice: 12,
            unit: "capsules",
            lowStockThreshold: 10,
            expiryDays: -3,
            isActive: true,
        },
        {
            key: "b_aspirin",
            pharmacyId: pharmacyProfiles[1].id,
            medicineName: "Aspirin",
            dosage: "75mg",
            genericName: "Acetylsalicylic Acid",
            category: "Cardiac",
            manufacturer: "Bayer",
            batch: "AS2412",
            stockQuantity: 64,
            unitPrice: 5.25,
            unit: "tablets",
            lowStockThreshold: 15,
            expiryDays: 210,
            isActive: true,
        },
        {
            key: "b_vitamin_d3",
            pharmacyId: pharmacyProfiles[1].id,
            medicineName: "Vitamin D3",
            dosage: "60000IU",
            genericName: "Cholecalciferol",
            category: "Supplements",
            manufacturer: "Abbott",
            batch: "VD2388",
            stockQuantity: 32,
            unitPrice: 28,
            unit: "sachets",
            lowStockThreshold: 10,
            expiryDays: 155,
            isActive: true,
        },
        {
            key: "b_losartan",
            pharmacyId: pharmacyProfiles[1].id,
            medicineName: "Losartan",
            dosage: "50mg",
            genericName: "Losartan Potassium",
            category: "Blood Pressure",
            manufacturer: "Torrent",
            batch: "LS2203",
            stockQuantity: 4,
            unitPrice: 7.5,
            unit: "tablets",
            lowStockThreshold: 8,
            expiryDays: 30,
            isActive: true,
        },
        {
            key: "b_ors",
            pharmacyId: pharmacyProfiles[1].id,
            medicineName: "ORS",
            dosage: "21g",
            genericName: "Oral Rehydration Salts",
            category: "Hydration",
            manufacturer: "FDC",
            batch: "OR2420",
            stockQuantity: 0,
            unitPrice: 18,
            unit: "sachets",
            lowStockThreshold: 6,
            expiryDays: 70,
            isActive: true,
        },
        {
            key: "c_ibuprofen",
            pharmacyId: pharmacyProfiles[2].id,
            medicineName: "Ibuprofen",
            dosage: "400mg",
            genericName: "Ibuprofen",
            category: "Pain Relief",
            manufacturer: "GSK",
            batch: "IB2399",
            stockQuantity: 40,
            unitPrice: 6,
            unit: "tablets",
            lowStockThreshold: 12,
            expiryDays: 100,
            isActive: false,
        },
        {
            key: "c_cetrizine",
            pharmacyId: pharmacyProfiles[2].id,
            medicineName: "Cetirizine",
            dosage: "10mg",
            genericName: "Cetirizine Hydrochloride",
            category: "Allergy",
            manufacturer: "Alkem",
            batch: "CT2418",
            stockQuantity: 11,
            unitPrice: 4.5,
            unit: "tablets",
            lowStockThreshold: 10,
            expiryDays: 65,
            isActive: false,
        },
    ];

    for (const row of inventoryRows) {
        const expiryDate = ctx.shiftDate(ctx.now, row.expiryDays, 0, 0);
        const inventoryId = ctx.buildDocId("inventory", row.key);

        docs.push(
            ctx.makeSeedDoc(
                "pharmacies",
                `pharmacyInventory/${inventoryId}`,
                ctx.withSeedMeta({
                    pharmacyId: row.pharmacyId,
                    medicineName: row.medicineName,
                    medicineNameNormalized: row.medicineName.toLowerCase(),
                    dosage: row.dosage,
                    genericName: row.genericName,
                    category: row.category,
                    manufacturer: row.manufacturer,
                    batchNumber: row.batch,
                    stockQuantity: row.stockQuantity,
                    quantity: row.stockQuantity,
                    unitPrice: row.unitPrice,
                    unit: row.unit,
                    lowStockThreshold: row.lowStockThreshold,
                    expiryDate,
                    isActive: row.isActive,
                    createdAt: ctx.dateAt(-40, 9, 15),
                    updatedAt: ctx.now,
                }),
                []
            )
        );
    }

    ctx.refs.pharmacies = {
        approved: pharmacyProfiles[0],
        pending: pharmacyProfiles[1],
        rejected: pharmacyProfiles[2],
        list: pharmacyProfiles,
    };

    return docs;
}

module.exports = {
    buildPharmacyDocs,
};
